[project]
name = "maqam-cheatsheet"
version = "0.0.1"
requires-python = ">=3.11"

[tool.ruff]
line-length = 79

[tool.mypy]
disable_error_code = ["attr-defined"]
strict = true

[tool.black]
line-length = 79

[tool.setuptools]
py-modules = ["maqamat"]
