[project]
name = "maqam-cheatsheet"
version = "0.0.1"
requires-python = ">=3.11"

[tool.ruff]
line-length = 89

[tool.mypy]
disable_error_code = ["attr-defined"]

[tool.black]
line-length = 89

[tool.setuptools]
py-modules = ["maqamat"]
