#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

setup() {
    test -f .venv || python -m venv .venv
    .venv/bin/pip install -r requirements.txt
    mkdir -p out
    test -f out/alpine.min.js || curl -L unpkg.com/alpinejs > out/alpine.min.js
}

serve() {
    .venv/bin/python -m http.server 42488 --bind 127.0.0.1 --directory out
}

watch-build() {
    watchexec -w static -w data -w templates -w maqamat.py  \
      --ignore "*.mo" -- ./tasks build
}

build() {
    .venv/bin/pybabel compile --domain=translations --directory=data/locale --use-fuzzy
    cp static/js/index.js static/style.css static/img/* static/svg/* out
    .venv/bin/python maqamat.py
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | awk '!/^_/{ print "  " $0 }' | cat
}

"${@:-help}"
